### ISSUE TITLE
Clicking on "WebSight.io" logo while logged in returns to login screen

### ISSUE THREAD

**Issue by jwwsc** [lavalamp-/ws-backend-community#27]
I clicked on the "WebSight.io" logo in the upper left while logged in, thinking it would bring me to the home page/dashboard page. Instead, it brought me to the login page, although it did not log me out.

**Comment by lavalamp-** [comment]
Fixed in frontend at https://github.com/lavalamp-/ws-frontend-community/commit/9c7a7179d97443bd1237ea1a4bec93d371bd6ad2
