### ISSUE TITLE
Username and Password not passed into Elasticsearch

### ISSUE THREAD

**Issue by fatalglitch** [lavalamp-/ws-backend-community#36]
https://github.com/lavalamp-/ws-backend-community/blob/20177fc9e35101b16dc68005e48c4d649b419cb1/lib/config.py#L618

This code doesn't pass in the username and password to Elasticsearch, which causes authentication failures.

**Comment by lavalamp-** [comment]
Thanks for reporting this issue.

Authenticating to Elasticsearch can be done through setting the following configuration values in the [Elasticsearch] section:

```
es_use_http_auth = True
es_username = elastic
es_password = password
```

The commented out components of the ES URL are (I believe) from an older method of authentication that Elasticsearch supported. Regardless of the cause of the commented lines, I've tested that the HTTP authentication method supported by the configuration values above is working.
